id: AE83A78BC
title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik Labdrön'
type: translation
pechas:
- I7183DE33
- I4D4448D5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:04.146709
  last_modified_at: 2023-01-04 13:01:04.146724
  collections:
  - Machik Labdrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I7183DE33/225F: DDCF
  I4D4448D5/FD82: DDCF
